README.md

improve install instruction

---

src/Ui/UiRequest.py

Fix readdress loop

---

plugins/Sidebar/SidebarPlugin.py

https://github.com/zeronet-conservancy/zeronet-conservancy/issues/30

[Sidebar] "Open site directory" feature

---

README.md

not preinstalled on some OS and causes error on 0net installation

add pkg-config dependency #46

---

src/Ui/media/all.css
src/Ui/template/wrapper.html

this logic of the top right button is bit simpler for me. also includes latest branding updates.

Top right button vision

---

.dockerignore
.gitignore
Dockerfile

Add:
- .dockerignore
Fix:
- Dockerfile - update python version, build app in venv. Build work in x86 and arm64 (M1) arch.

Fix dockerfile

---

README-ptbr.md

I translated the README file into Brazilian Portuguese
I would like to help with the translation of more documentation, I am a native speaker of Portuguese and could help with the documentation.
I'm learning to use github so I still have a little difficulty understanding the branches but I want to gain experience and learn as much as possible from the tool

iFallenHunt translation

---

termux.sh

Instructions:
1. Download the script (termux.sh) in termux
3. Run it

Add script for running zeronet-conservancy in Termux on Android

---

requirements.txt
src/Peer/PeerPortchecker.py
src/util/UpnpPunch.py

return upnp punch using secure xml library

---

src/Content/ContentManager.py

parse json (which is required anyway) instead of ad-hock
re-based parsing

Fix `modified` parsing

---

README.md

This dependency installing fixed my issue #129

add libffi-dev dependency

---

README.md

these are required e.g. on Tails, although I still couldn't get
0net to work on it yet
Signed-off-by: caryoscelus <caryoscelus@gmx.com>

Add more deb-based dependencies

---

src/Config.py
src/Connection/Connection.py
src/Content/ContentManager.py

replace version with generic `user_agent` that will remain constant

reduce fingerprinting of site owner

---

plugins/ContentFilter/ContentFilterPlugin.py

ask for optional mute reason

---

src/Config.py
src/main.py
zeronet.py

minor code improvements

---

CHANGELOG.md
src/main.py

fix regression introduced in https://github.com/zeronet-conservancy/zeronet-conservancy/commit/8913363ca8f6b65e62f7a6a6c8b052b4952e74b5
fixes https://github.com/zeronet-conservancy/zeronet-conservancy/issues/142

Fix parsing gh 142

---

plugins/disabled-NoNewSites/NoNewSites.py
plugins/disabled-NoNewSites/__init__.py
plugins/disabled-NoNewSites/plugin_info.json

This is light-based version of --no-new-sites option in Multiuser plugin

No new sites plugin

---

src/Content/ContentManager.py
src/Site/SiteManager.py

replace local imports with global ones to improve readability (and possibly even performance)

Minor improvements

---

src/Config.py
src/Tor/TorManager.py
src/main.py

allow only passing port as tor_* parameters

---

plugins/Sidebar/SidebarPlugin.py

copy local onion peer from sidebar

---

plugins/Sidebar/SidebarPlugin.py

add support for ada/cardano donation addresses in sidebar

---

src/Db/Db.py
src/Site/Site.py
src/Ui/UiRequest.py

plus remove outdated line of code that triggers warning

redirect bit domains

---

plugins/Zeroname/SiteManagerPlugin.py
src/Config.py

use archived version of .bit domain list (deprecated) by default

---

src/Config.py
src/Site/Site.py

Fix sha1 trackers

---

src/Peer/Peer.py

report error when peer rejects our update

---

src/Ui/UiRequest.py

Fix /raw readdress

---

src/Ui/UiRequest.py

don't fail if http_accept header is */*

---

src/Peer/PeerPortchecker.py
src/util/UpnpPunch.py

thanks to 0netdwf for reporting

more anonymous upnp

---

src/Content/ContentManager.py
src/Db/Db.py

Wake up, it's 2023 now. Also f-strings has been used prominently already

Drop attempts at py<3.6 compatibility

---

plugins/Sidebar/ConsolePlugin.py
src/util/SafeRe.py

integrate ReDoS fix from ZNE and improve code

Improve SafeRe

---

plugins/ContentFilter/ContentFilterPlugin.py
plugins/ContentFilter/ContentFilterStorage.py

fixes https://github.com/HelloZeroNet/ZeroNet/issues/1855

Remove and don't update muted users' content

---

src/Config.py

- using underscore is deprecated but still works
- also don't override commandline --open-browser option

Use dashes in command line options instead of underscore

---

src/Worker/Worker.py

Fix py3.9 compatibility

---

src/Config.py
src/File/FileServer.py
src/Ui/UiRequest.py
src/util/helper.py

Not sure about implementation, but it works

fix IPv6 validation #263

---

README-ja.md
README-ptbr.md
README-ru.md
README-zh-cn.md
README.md

I created Japanese translated README.

docs: add Japanese README
